knpu_oauth2_client:
  clients:
    keycloak:
      type: generic
      provider_class: Stevenmaguire\OAuth2\Client\Provider\Keycloak
      provider_options:
        authServerUrl: '%env(KEYCLOAK_BASE_URL)%'
        realm: '%env(KEYCLOAK_REALM)%'
      client_id: '%env(OAUTH_KEYCLOAK_CLIENT_ID)%'
      client_secret: '%env(OAUTH_KEYCLOAK_CLIENT_SECRET)%'
      redirect_route: connect_auth_check
      redirect_params: { }