knpu_oauth2_client:
  clients:
    discord:
      type: discord
      client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
      client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
      redirect_route: connect_discord_check
      redirect_params: { }
    github:
      type: github
      client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
      client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
      redirect_route: connect_github_check
      redirect_params: { }